language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - nightly

notifications:
  email: false
sudo: false

after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("GeometryTypes")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder()); Codecov.submit(process_folder())'
  # Documenter auto-deploy
  # following `using` instruction is for triggering precompilation
  - julia -e 'ps=Pkg.PackageSpec(name="Documenter", version="0.19"); Pkg.add(ps); Pkg.pin(ps)'
  - julia -e 'cd(Pkg.dir("GeometryTypes", "docs")); include("make.jl")'
