language: julia
os: osx
osx_image: xcode7.3
julia:
    - 0.7
    - 1.0
    - nightly
notifications:
    email: false
after_success:
    - julia -e 'cd(Pkg.dir("Homebrew")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
