#!/bin/bash

echo "flake8 all python file here"

for f in *.py
do
  flake8 $f
done

#function aggressive_lint() {
#  
#}

function auto() {
  for f in *.py
  do
    autopep8 --in-place --aggressive --aggressive $f
  done
}

function ask() {
  echo "press l for linting, n to pass"
  read -n1 input

  if [ -z $input] ; then
    
    echo "autopep8 denied"
    exit

  elif [ $input = 'l'] || [ $input = 'L' ] ; then
    auto
    exit

  else
    exit
  
  fi
}


ask
