language: julia
os:
    - linux
    - osx
julia:
    - 0.7
    - 1.0
    - nightly
notifications:
    email: false
sudo: false
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia -e 'using Pkg; Pkg.clone(pwd())'
    - julia -e 'using Pkg; Pkg.test("Mustache", coverage=true)'
after_success:
    - julia -e 'cd(Pkg.dir("Mustache")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
