language: julia
os:
    - osx
    - linux
julia:
    - 0.7
    - 1.0
    - nightly
notifications:
    email: false
jobs:
  include:
    - stage: deploy
      julia: 0.7
      os: linux
      script:
        - julia -e 'mv("_Project.toml", "Project.toml")'
        - julia -e 'import Pkg; Pkg.build()'
        - julia -e 'import Pkg; Pkg.add("Documenter")'
        - julia docs/make.jl
after_success:
    - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
