language: julia
sudo: false
julia:
    - 0.7
    - 1.0
    - nightly
after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("Interpolations")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("Interpolations")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
