# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

services:
 - mysql

os:
  - linux

julia:
  - 1.0
  - nightly

notifications:
  email: false

after_success:
  # push coverage results to Coveralls
  #- julia -e 'cd(Pkg.dir("MySQL")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'using Pkg; cd(Pkg.dir("MySQL")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'

before_script:
- export OLD_PATH=$LD_LIBRARY_PATH
- export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:`mysql_config --libs | cut -d ' ' -f1 | sed 's/-L//'`

after_script:
- export LD_LIBRARY_PATH=$OLD_PATH
- unset OLD_PATH
