language: julia
os:
  - linux
julia:
  - 0.6
  - 0.7
  - nightly
matrix:
  fast_finish: true
  allow_failures:
    - julia: nightly
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.build("Gadfly");'
  - julia -e 'Pkg.checkout("Compose")'
  - julia --check-bounds=yes -e 'Pkg.test("Gadfly", coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("Gadfly")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
  - julia -e 'Pkg.checkout("Compose")'
  - if [[ "$TRAVIS_JULIA_VERSION" == "0.6" ]]; then julia -e 'cd(Pkg.dir("Gadfly")); map(x->Pkg.add(strip(x)), readlines(open(joinpath("docs", "REQUIRE")))); include(joinpath("docs", "make.jl"))'; fi
